require("dotenv").config()
const express=require("express")
const userRouter = require("./routes/user.routes")
const cors=require("cors")
const cookieParser=require("cookie-parser")
const connectDB = require("./db/connectDB")
const productRouter = require("./routes/product.routes")
const shopRouter = require("./routes/shop.routes")
const cartRouter = require("./routes/cart.routes")
const addressRouter = require("./routes/address.routes")
const orderRouter = require("./routes/order.routes")
const adminOrderRouter = require("./routes/admin.order.routes")
const searchRouter = require("./routes/search.routes")
const reviewRouter = require("./routes/review.routes")
const app=express()
app.use(express.json())
app.use(cors({
    origin:"http://localhost:5173",
    credentials:true
}))
app.use(cookieParser())
app.use("/api/user",userRouter)
app.use("/api/admin/products",productRouter)
app.use("/api/shop",shopRouter)
app.use("/api/shop/cart",cartRouter)
app.use("/api/shop/address",addressRouter)
app.use("/api/shop/order",orderRouter)
app.use("/api/admin/orders",adminOrderRouter)
app.use("/api/shop/search",searchRouter)
app.use("/api/products",reviewRouter)

connectDB()
app.listen(process.env.PORT,()=>console.log(`server started running on port ${process.env.PORT}`))
